const FETCH_ALL_FOODS = "FETCH_ALL_FOODS";
const CREATE_FOOD = "CREATE_FOOD";
const UPDATE_FOOD = "UPDATE_FOOD";
const DELETE_FOOD = "DELETE_FOOD";

const FETCH_ALL_MEALS = "FETCH_ALL_MEALS";
const CREATE_MEAL = "CREATE_MEAL";
const UPDATE_MEAL = "UPDATE_MEAL";
const DELETE_MEAL = "DELETE_MEAL";

const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

//const LIKE_STORY = "LIKE_STORY";

export {
    FETCH_ALL_FOODS,
    CREATE_FOOD,
    UPDATE_FOOD,
    DELETE_FOOD,
    FETCH_ALL_MEALS,
    CREATE_MEAL,
    UPDATE_MEAL,
    DELETE_MEAL,
    AUTHENTICATION,
    LOGOUT
}